apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: restrict-egress
  namespace: online-boutique
spec:
  endpointSelector:
    matchLabels: {} # Applies to all pods in the namespace
  egress:
    # ---------------------------------------------------------
    # 1. Core Infrastructure: DNS
    # ---------------------------------------------------------
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
      - ports:
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP

    # ---------------------------------------------------------
    # 2. Application Logic: Intra-Namespace Communication
    # ---------------------------------------------------------
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": online-boutique

    # ---------------------------------------------------------
    # 3. Identity & Auth: GKE Metadata Server
    # ---------------------------------------------------------
    - toCIDR:
      - "169.254.169.254/32"
      toPorts:
      - ports:
        - port: "80"
          protocol: TCP

    # ---------------------------------------------------------
    # 4. Observability: Google Cloud APIs
    # ---------------------------------------------------------
    - toFQDNs:
      - matchName: "monitoring.googleapis.com"
      - matchName: "cloudtrace.googleapis.com"
      - matchName: "logging.googleapis.com"
      toPorts:
      - ports:
        - port: "443"
          protocol: TCP

    # ---------------------------------------------------------
    # 5. Service Mesh: Istio Control Plane & Ingress
    # ---------------------------------------------------------
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": istio-system
      - matchLabels:
          "k8s:app": istio-ingressgateway
      - matchLabels:
          "k8s:istio": ingressgateway
    - toServices:
      - k8sService:
          serviceName: istiod
          namespace: istio-system

    # ---------------------------------------------------------
    # 6. Localhost (Required for Istio Sidecar)
    # Reference: https://github.com/cilium/cilium/issues/18465
    # ---------------------------------------------------------
    - toCIDR:
      - "127.0.0.1/32"
